<a href="https://colab.research.google.com/github/Moonnightgh/Dhv/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

In [19]:
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d.shape)
print(array_1d.size)
print(array_1d.ndim)
print(len(array_1d))
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])
print(array_2d.shape)
print(array_2d.size)
print(array_2d.ndim)
print(len(array_2d))
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],

                     [[7, 8, 9],
                      [10, 11, 12]]])
print(array_3d.shape)
print(array_3d.size)
print(array_3d.ndim)
print(len(array_3d))


(5,)
5
1
5
(2, 3)
6
2
2
(2, 2, 3)
12
3
2


In [18]:
a_example = np.arange(1, 10, 2)
print(a_example)
randint_example = np.random.randint(1, 100, size=(3, 3))
print(randint_example)
rand_example = np.random.rand(2, 3)
print(rand_example)
lspace_example = np.linspace(1, 10, num=5)
print(lspace_example)
ones_example = np.ones((2, 3))
print(ones_example)
zeros_example = np.zeros((3, 2))
print(zeros_example)
diag_example = np.diag([1, 2, 3])
print(diag_example)

[1 3 5 7 9]
[[20 40 86]
 [35 11 50]
 [71 86 12]]
[[0.17955411 0.41000119 0.06876553]
 [0.94692931 0.67113382 0.17596124]]
[ 1.    3.25  5.5   7.75 10.  ]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [20]:
marks= np.random.randint(0, 101, size=10)
print(marks)

[ 1 49 23 56  7 23 63 89 20 57]


In [21]:
f_marks= marks[marks < 30]
print(f_marks)


[ 1 23  7 23 20]


In [22]:
print(f_marks)
pmarks=marks[marks>=30]
print(pmarks)
rows = 3
cols = 4
random_2d_array = np.random.rand(rows, cols)
print(random_2d_array)


[ 1 23  7 23 20]
[49 56 63 89 57]
[[0.91971561 0.98050675 0.62778071 0.30442703]
 [0.9810799  0.81871331 0.97123993 0.34049479]
 [0.14933831 0.32669519 0.18643396 0.71478149]]
